---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
fig <- plot_ly(
  type = 'scatter',
  x = rest_inspec$cuisine_description,
  y = rest_inspec$score,
  mode = 'markers',
  transforms = list(
    list(
      type = 'aggregate',
      groups = rest_inspec$cuisine_description,
      aggregations = list(
        list(
          target = 'y', func = 'sum', enabled = T
        )
      )
    )
  )
)

fig

```

### Chart C

```{r}
critical%>% 
  count(cuisine_description) %>% 
  mutate(boro= fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "viridis")

```
```

